In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns


- It contains value- and equal-weighted returns for 48 industry portfolios.
- The portfolios are constructed at the end of June.
- The annual returns are from January to December.
- Missing data are indicated by -99.99 or -999.

### Data Import

In [2]:
df_raw = pd.read_csv('48_Industry_Portfolios_Daily.csv', skiprows=range(0,9))
df_raw.drop(axis=0, labels=range(25292,len(df_raw)), inplace=True)
df_raw

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


Unnamed: 0    Agric    Food     Soda     Beer     Smoke    Toys   \
0       19260701     0.56    -0.07   -99.99    -1.39      0.0    -1.44   
1       19260702     0.29     0.06   -99.99     0.78      0.7     1.46   
2       19260706    -0.33     0.18   -99.99    -1.74      0.5    -0.96   
3       19260707     3.57    -0.15   -99.99    -1.73    -0.12    -0.49   
4       19260708      0.3     1.12   -99.99    -0.15      0.3    -0.49   
...          ...      ...      ...      ...      ...      ...      ...   
25287   20220725     2.69     0.98     0.99     0.09     0.53    -1.31   
25288   20220726    -0.28     0.69     1.36     0.92     0.71    -3.67   
25289   20220727     1.88    -0.07     0.04     0.28     0.19     3.99   
25290   20220728     0.50     1.63     1.68     1.69     0.10     1.51   
25291   20220729     0.82     0.55     0.35     0.07    -0.13    -3.51   

         Fun      Books    Hshld  ...    Boxes    Trans    Whlsl    Rtail  \
0         0.62    -1.27     -0.9  ...    -0.93     0.14     2.77    -0.02   
1         0.03      0.0    -0.34  ...     1.07     0.07      0.0     0.01   
2        -0.06     4.27     -1.2  ...     0.73     -0.2     0.77    -0.22   
3        -0.06     -4.1    -0.22  ...     2.22     0.18    -3.21    -0.57   
4         0.24      0.0    -0.01  ...    -0.39     0.46     -1.1    -0.38   
...        ...      ...      ...  ...      ...      ...      ...      ...   
25287    -0.39     0.34     0.28  ...     0.28     0.60     0.59    -0.69   
25288    -2.31    -0.51    -0.49  ...    -0.53    -1.76    -0.58    -4.50   
25289     4.16     3.22     1.27  ...     2.23     1.78     1.49     3.24   
25290     0.25     0.65     1.78  ...     1.27     1.81     1.58     1.39   
25291    -0.04     0.46    -3.64  ...     0.39     1.98     1.30     4.67   

         Meals    Banks    Insur    RlEst    Fin      Other  
0         0.27     0.59     0.47     0.81     0.57    -1.66  
1         -0.1     1.04    -0.03    -0.61    -1.03     3.09  
2        -0.67     0.45     0.31    -0.72     0.62     1.41  
3        -1.08    -1.09     0.21     0.07     0.17     0.62  
4         0.33     0.99    -0.88    -0.36     -1.1     0.98  
...        ...      ...      ...      ...      ...      ...  
25287    -1.08     0.79     1.30     0.52     0.31     0.58  
25288    -0.09    -1.55     0.03    -1.88    -1.79    -0.26  
25289     3.54     1.36     0.51     2.41     1.88     1.51  
25290     1.66     0.12     0.39     1.27     3.13     2.20  
25291     0.52     1.04     0.80     0.55     1.22     1.60  

[25292 rows x 49 columns]

### Data Cleaning

In [3]:
df = df_raw.copy()
df = df.apply(pd.to_numeric)
df.rename(columns={'Unnamed: 0':'Date'}, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 25292 entries, 0 to 25291
Data columns (total 49 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    25292 non-null  int64  
 1   Agric   25292 non-null  float64
 2   Food    25292 non-null  float64
 3   Soda    25292 non-null  float64
 4   Beer    25292 non-null  float64
 5   Smoke   25292 non-null  float64
 6   Toys    25292 non-null  float64
 7   Fun     25292 non-null  float64
 8   Books   25292 non-null  float64
 9   Hshld   25292 non-null  float64
 10  Clths   25292 non-null  float64
 11  Hlth    25292 non-null  float64
 12  MedEq   25292 non-null  float64
 13  Drugs   25292 non-null  float64
 14  Chems   25292 non-null  float64
 15  Rubbr   25292 non-null  float64
 16  Txtls   25292 non-null  float64
 17  BldMt   25292 non-null  float64
 18  Cnstr   25292 non-null  float64
 19  Steel   25292 non-null  float64
 20  FabPr   25292 non-null  float64
 21  Mach    25292 non-null  float64
 22

In [4]:
#making the date column into actual date 
df['Date'] = df['Date'].astype(str)
df['Date'] = df['Date'].apply(lambda x: (x[:4] + '-' + x[4:6] + '-' + x[6:]))
df['Date'] = pd.to_datetime(df['Date'])
df.head()


Date  Agric  Food   Soda   Beer   Smoke  Toys   Fun    Books  Hshld  \
0 1926-07-01   0.56  -0.07 -99.99  -1.39   0.00  -1.44   0.62  -1.27  -0.90   
1 1926-07-02   0.29   0.06 -99.99   0.78   0.70   1.46   0.03   0.00  -0.34   
2 1926-07-06  -0.33   0.18 -99.99  -1.74   0.50  -0.96  -0.06   4.27  -1.20   
3 1926-07-07   3.57  -0.15 -99.99  -1.73  -0.12  -0.49  -0.06  -4.10  -0.22   
4 1926-07-08   0.30   1.12 -99.99  -0.15   0.30  -0.49   0.24   0.00  -0.01   

   ...  Boxes  Trans  Whlsl  Rtail  Meals  Banks  Insur  RlEst  Fin    Other  
0  ...  -0.93   0.14   2.77  -0.02   0.27   0.59   0.47   0.81   0.57  -1.66  
1  ...   1.07   0.07   0.00   0.01  -0.10   1.04  -0.03  -0.61  -1.03   3.09  
2  ...   0.73  -0.20   0.77  -0.22  -0.67   0.45   0.31  -0.72   0.62   1.41  
3  ...   2.22   0.18  -3.21  -0.57  -1.08  -1.09   0.21   0.07   0.17   0.62  
4  ...  -0.39   0.46  -1.10  -0.38   0.33   0.99  -0.88  -0.36  -1.10   0.98  

[5 rows x 49 columns]

### Linear Algebra 

In [5]:
arr_len = 6


#first vector
eq_w = np.full(
    shape = arr_len,
    fill_value = 1/arr_len
)
print(eq_w)


#N matrix 
tmp1 = np.identity((arr_len-1), dtype='int64')
tmp2 = -np.ones((arr_len-1), dtype='int64')
eq_mat = np.append(tmp1,[tmp2], axis=0)
print(eq_mat)


#Beta vector 






[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
[[ 1  0  0  0  0]
 [ 0  1  0  0  0]
 [ 0  0  1  0  0]
 [ 0  0  0  1  0]
 [ 0  0  0  0  1]
 [-1 -1 -1 -1 -1]]


## Split data 

In [6]:
from sklearn.linear_model import *
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold 
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.metrics import *

In [25]:
# selecting only the most recent 63 days 
date = '2022-01-03'
no_obj = 63
date_i = df[df['Date'] == date].index[0]

q1 = df.copy()
q1 = q1.iloc[date_i-63:date_i,:]
q1

Date  Agric  Food   Soda   Beer   Smoke  Toys   Fun    Books  \
25085 2021-10-04  -2.01   0.10  -0.39  -0.35   0.57  -3.49  -1.91  -1.11   
25086 2021-10-05   1.91   0.75   0.51   0.36  -0.13   1.07   2.83   0.94   
25087 2021-10-06  -2.85   1.00   1.03   1.84   0.38   1.78   0.11  -0.08   
25088 2021-10-07   1.04  -0.07   0.36   1.08  -0.63   2.05  -0.17   1.80   
25089 2021-10-08   0.48  -0.48   0.09  -0.01   0.00  -1.04  -0.31   0.08   
...          ...    ...    ...    ...    ...    ...    ...    ...    ...   
25143 2021-12-27   1.23   0.71   0.77   0.84   0.48  -0.43  -0.29   1.04   
25144 2021-12-28   0.85   0.94   0.25   0.51   0.68  -0.72  -0.71   0.16   
25145 2021-12-29  -0.28   0.25   0.28   0.37   0.31  -0.73  -0.17  -0.15   
25146 2021-12-30  -0.41  -0.04  -0.28  -0.09  -0.14   2.91   0.71   0.07   
25147 2021-12-31   0.37   0.71   0.70   0.55   0.61  -1.02  -1.06  -0.32   

       Hshld  ...  Boxes  Trans  Whlsl  Rtail  Meals  Banks  Insur  RlEst  \
25085  -0.66  ...   0.20  -0.48  -0.43  -1.83  -0.97  -0.80  -1.01  -2.60   
25086   0.48  ...   1.39   1.24   0.48   0.66   0.36   1.07   1.56   0.99   
25087   0.88  ...   0.23   1.05  -0.71   0.57   0.50   0.31   0.34  -1.41   
25088   0.69  ...   0.51   0.00   1.73   1.40   0.76   0.71   1.56   1.35   
25089  -0.55  ...  -1.12   0.48  -0.01  -0.36  -0.60   0.37   0.63  -1.13   
...      ...  ...    ...    ...    ...    ...    ...    ...    ...    ...   
25143   1.16  ...   1.84   0.80   1.71   0.40   0.99   0.79   1.00   1.22   
25144   0.45  ...   1.49   0.18   0.26   0.49  -0.01  -0.04   0.43  -0.34   
25145   0.70  ...   0.82   0.20   0.70   0.10   0.14  -0.08   0.41   0.35   
25146  -0.64  ...  -0.04  -0.27  -0.49  -0.03  -0.10  -0.17  -0.32   0.21   
25147   0.59  ...   0.77   0.29   0.39  -0.20   0.25  -0.19  -0.28  -0.11   

       Fin    Other  
25085  -1.80  -0.78  
25086   2.41   1.10  
25087   0.13   0.54  
25088   1.01   1.17  
25089   0.67   0.08  
...      ...    ...  
25143   1.17   0.67  
25144  -0.38   0.42  
25145  -0.82   0.23  
25146  -0.15   0.09  
25147  -0.20  -0.09  

[63 rows x 49 columns]

In [ ]:
# select the 6 industries that we want 

In [ ]:
# split the data (make sure it is by rows)
R_train, R_test = train_test_split()

In [ ]:
# calculate demeaned R (might not need to do)

In [ ]:
# calculate the y

In [ ]:
# calculate X

In [ ]:
# pass it to fit the model

In [ ]:
# then do cross validation to show over fitting